### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by blemasso** [algohary/SlicerExtension_ColiageFilter#1]
Hi,

I downloaded the slicerExtension_coliageFilter as a zip file.
The I use this procedure to install the extension (from step 2)
https://www.slicer.org/wiki/Documentation/Nightly/SlicerApplication/ExtensionsManager#Installing_an_extension_without_network_connection

But I have the following error error :
"_**No extension description found in archive '
.../Downloads/SlicerExtension_ColiageFilter.zip**_'"

Did I do something wrong?

Best,
Benjamin

ps: I have a MacOs (newest one) and the slicer version is 4.5.0-1 r24735

**Comment by algohary** [comment]
Hi Benjamin, 
A new version with an updated prebuilt package is uploaded. Please let me know if you still have issues.
Thanks,
Ahmad Algohary, MS
Medical Image Analysis
Solutions Architect
CCIPD, BME, CWRU

**Comment by alps1122** [comment]
Hi,
I have the same problem as Benjamin.And the slicer version is 4.8.1 r26813,windows.
Which version of the slicer are you using?

Best,
Hui

**Comment by algohary** [comment]
Hi Hui,

Code is updated now to work on the latest 3D Slicer version 4.11.xx with code build instructions and prebuilt package.

Regards,
Ahmad

**Comment by alps1122** [comment]
Hi Ahmad,
I’m  sorry that I don’t know how to install it. There is still an error on 3Dslicer version 4.11.0:

The following is my installation steps
1.download:
[cid:image004.jpg@01D47080.00C348F0]
2.install
[cid:image005.png@01D4707F.8AE814D0]

3.and the error:
[cid:image002.png@01D4707E.E8E48E70]
Besides, I’m not sure whether it need to be compiled and I don’t know how to compile.
Could you give me an installation tutorial?

Best,
Hui
发件人: algohary <notifications@github.com>
发送时间: 2018年10月30日 14:19
收件人: algohary/SlicerExtension_ColiageFilter <SlicerExtension_ColiageFilter@noreply.github.com>
抄送: 冯慧 <alps1122@i.smu.edu.cn>; Comment <comment@noreply.github.com>
主题: Re: [algohary/SlicerExtension_ColiageFilter] Installation issues (#1)


Hi Hui,

Code is updated now to work on the latest 3D Slicer version 4.11.xx with code build instructions and prebuilt package.

Regards,
Ahmad

**Comment by algohary** [comment]
Hi Hui,

Please follow the instructions on 
https://github.com/algohary/SlicerExtension_ColiageFilter/wiki/Prebuilt-Package-Installation
and let me know if you still have issues.

Regards,
Ahmad
