### ISSUE TITLE
How could I fix the error on COLIAGE Texture Radiomics?  + Additional question for radius

### ISSUE THREAD

**Issue by Yaewon-Park** [algohary/SlicerExtension_ColiageFilter#2]
Hello, I'm Yaewon Park.
1.  Sorry for bugging you again and asking you questions.. 
 
 After your help (thank you!) , I successfully installed COLIAGE extension in the 3D slicer program.

 However, after executing the program with a T1C.nii.gz image file and an input ROI mask, there's still an error,

 1)  Input : Patientno_T1C.nii.gz (which is a normal nii.gz file, working well on other packages)
 Input mask: Patientno_T1C.nii.gz-label (ROI label file in 3D slicer)

 Output image: Output image (creating new output image)
 Radius: 5 (tried a few other radius such as 2 or 10)

 2) 
 After execution, there's an error message saying:

 COLIAGE Texture Radiomics standard error:
 PARSE ERROR:
 One or more required arguments missing!

 Brief USAGE:
 For complete USAGE and HELP type:
 C:/Program Files/Slicer 4.11.0-2018-11-02/bin../lib/Slicer-4.11/cli-modules/CLIMOdule_ColiageFilter.exe --help

 -> How can I solve this problem? what is the reason of the error?
 (Because I couldn't upload the capture file in this issue forum, I uploaded the caputure image showing the erro in another site and here's the link:

https://www.evernote.com/Home.action?login=true#n=b1bcbf51-06de-485f-8c3b-777f1c1a1f1a&s=s684&ses=4&sh=2&sds=5& )

 Thank you again for your help. :D

2) Which is the optimized set for radius?
 I think there's probably no standard radius for radiomics texture analysis and you have to try multiple bins and compare the performance.
 Is this right? Or is there a optimized radius you recommend?

**Comment by satishev** [comment]
Hi, wanted to provide an update -- we have now completely rewritten this in Python.

This new release is being more actively developed and we will be working to better integrate it with platforms such as 3D Slicer.

Please check out the repo here: https://github.com/radxtools/collageradiomics
Docker images and Jupyter notebooks are provided to make it easier to run.
Any issues you face with using/building it should be raised at the corresponding issue tracker: https://github.com/radxtools/collageradiomics/issues
