### ISSUE TITLE
Plugin caused Slicer3D to crash

### ISSUE THREAD

**Issue by haanme** [algohary/SlicerExtension_ColiageFilter#3]
Hi

I installed plug-in successfully but when using GUI, two Nifti Images (FLAIR, binary mask), the Slicer3D crashed ungraciously (i. e. just exited without error message). For that same reason I cannot give more detailed information.

System information:
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.17134 Build 17134
System Type	x64-based PC

Slicer version: Slicer 4.10.0

very best regards
Harri M

**Comment by algohary** [comment]
Hi Harry,

Please update to the latest version of Slicer. If you still have the problem, please share the images and we’ll let you know once the issue is resolved.

Thanks,
Ahmad

**Comment by satishev** [comment]
Hi, wanted to provide an update -- we have now completely rewritten this in Python.

This new release is being more actively developed and we will be working to better integrate it with platforms such as 3D Slicer.

Please check out the repo here: https://github.com/radxtools/collageradiomics
Docker images and Jupyter notebooks are provided to make it easier to run.
Any issues you face with using/building it should be raised at the corresponding issue tracker: https://github.com/radxtools/collageradiomics/issues
