### ISSUE TITLE
Some question about  running the COLIAGE Texture

### ISSUE THREAD

**Issue by ywang336** [algohary/SlicerExtension_ColiageFilter#4]
Hi,

Thank you for sharing code on GitHub. I have some problems when I tried to run the COLIAGE Texture in 3D Slicer and I'm wondering if you can help me solve them.

When I used the COLIAGE Texture Radiomic in 3D Slicer and clicked the "Apply". It came out the error that "HEAP CORRUPTION DETECTED: after Normal block (#316184) at 0x0000000002ADF710. CRT detected that the application wrote to memory after end of heap buffer." And in the 3D Slicer it shows "COLlAGE Texture Radiomics standard error: PARSE ERROR: One or more required arguments missing!"

I have checked about this kind of error and others said this kind of problem may cause by wrong code of indicator, so it leads to the error of memory.

I'm wondering if this problem only appears on my computer and could you please help me on how to solve the problem and run it normally, either checking your code or teaching me what to do.

Thanks a lot.

Best,
Wang

By the way, my system is Win7 and Slicer is 4.10.2.

**Comment by ywang336** [comment]
Hi,

I updated my 3D Slicer to 4.11.0 today and tried again. There are something new in the error "[--returnparameterfile] [--processinformationaddress] [--xml] [--echo] [--deserialize ] [--serialize ] [--] [--version] [-h]". Could you please help me check what's going wrong? Thanks and looking forward to hearing from you.

Best,
Wang

ps: I'm from SBU.

**Comment by satishev** [comment]
Thank you for getting in touch regarding the issue. We will try testing this in Slicer at our end and get back to you.

You can also try running the CLI executable linked on our [download page](https://collageradiomics.com/download/), which should hopefully not give any errors.

**Comment by ywang336** [comment]
> Thank you for getting in touch regarding the issue. We will try testing this in Slicer at our end and get back to you.
> 
> You can also try running the CLI executable linked on our [download page](https://collageradiomics.com/download/), which should hopefully not give any errors.

**Comment by ywang336** [comment]
> Thank you for getting in touch regarding the issue. We will try testing this in Slicer at our end and get back to you.
> 
> You can also try running the CLI executable linked on our [download page](https://collageradiomics.com/download/), which should hopefully not give any errors.

Thanks for replying. I have tried to run the CLI executable just now and nothing happened after I double clicked it. Is it because the problem of my computer? Like lacking of some environment? Thank you again.

Best,
Wang

**Comment by satishev** [comment]
Please follow the instructions on the download page, you have to run it from the command line.

**Comment by ywang336** [comment]
> Please follow the instructions on the download page, you have to run it from the command line.

Thanks for helping very much. I have learned to run it from the command line, but it always said "The file doesn't exist." Do I need to put my images at a specific folder? Or I can put them anywhere?

Best,
Wang

**Comment by satishev** [comment]
The syntax is
> ../CollageFeatureExtractor2D.exe [input Arg 1] [input Arg 2] [input Arg 3] [input Arg 4]

These correspond to the following 4 inputs:
Input Arg. 1: Input Greyscale, meta Image, MR Image (.mha format or ITK compatible), including full path
Input Arg. 2: Input Binary, meta Image, Tumor label (.mha format or ITK compatible), including full path
Input Arg. 3: Neighborhood Radius (integer)
Input Arg. 4: Output feature map, meta image, including full path

**Comment by ywang336** [comment]
> The syntax is
> 
> > ../CollageFeatureExtractor2D.exe [input Arg 1] [input Arg 2] [input Arg 3] [input Arg 4]
> 
> These correspond to the following 4 inputs:
> Input Arg. 1: Input Greyscale, meta Image, MR Image (.mha format or ITK compatible), including full path
> Input Arg. 2: Input Binary, meta Image, Tumor label (.mha format or ITK compatible), including full path
> Input Arg. 3: Neighborhood Radius (integer)
> Input Arg. 4: Output feature map, meta image, including full path

Thanks again. May I ask can your CLI executable read a folder? Because our images are in the form of many dicom files in a folder for one image, and I can't just enter one path for the image. Is there some methods for me to read the folder?

Best,
Wang

**Comment by ywang336** [comment]
> The syntax is
> 
> > ../CollageFeatureExtractor2D.exe [input Arg 1] [input Arg 2] [input Arg 3] [input Arg 4]
> 
> These correspond to the following 4 inputs:
> Input Arg. 1: Input Greyscale, meta Image, MR Image (.mha format or ITK compatible), including full path
> Input Arg. 2: Input Binary, meta Image, Tumor label (.mha format or ITK compatible), including full path
> Input Arg. 3: Neighborhood Radius (integer)
> Input Arg. 4: Output feature map, meta image, including full path

Sorry for interrupting again. I have tried your case images and they ran successfully, but the mask area on output images became black. Is that the correct result of the CLI executable? And also I have two more question. Can this filter deal with 3D images in the 3D Slicer? Or it can only deal with 2D images as the CLI executable. And also is there any ways to read folders with CLI executable? We are really looking forward to learning this filter and using it to help us analyse images. Thank you for replying and hoping to hear from you.

Best,
Wang

**Comment by satishev** [comment]
> Sorry for interrupting again. I have tried your case images and they ran successfully, but the mask area on output images became black. Is that the correct result of the CLI executable? 

You mean the area _outside_ the mask area on the output image? Or the mask area itself?

> Can this filter deal with 3D images in the 3D Slicer? Or it can only deal with 2D images as the CLI executable. 

The CLI executable and the Slicer extension should both work with 3D volumes. Please try and let us know if they don't.

> And also is there any ways to read folders with CLI executable? 

I think the CLI executable works best the MHA files, which can be single 2D images or 3D volumes. I think we faced issues trying to provide an entire folder as an input and hence did not implement that. You could batch convert the folder of images into a single MHA volume - that should work as an input to COLLAGE.

**Comment by ywang336** [comment]
> > Sorry for interrupting again. I have tried your case images and they ran successfully, but the mask area on output images became black. Is that the correct result of the CLI executable?
> 
> You mean the area _outside_ the mask area on the output image? Or the mask area itself?
> 
> > Can this filter deal with 3D images in the 3D Slicer? Or it can only deal with 2D images as the CLI executable.
> 
> The CLI executable and the Slicer extension should both work with 3D volumes. Please try and let us know if they don't.
> 
> > And also is there any ways to read folders with CLI executable?
> 
> I think the CLI executable works best the MHA files, which can be single 2D images or 3D volumes. I think we faced issues trying to provide an entire folder as an input and hence did not implement that. You could batch convert the folder of images into a single MHA volume - that should work as an input to COLLAGE.

Thanks. It is the mask area itself which is black. As you can see in the printscreen below, the first is the image itself and the second is the output after CLI executable.

![slice1](https://user-images.githubusercontent.com/53053001/61722061-92d8d080-ad37-11e9-8384-623932d9f8d4.png)

![outslice1](https://user-images.githubusercontent.com/53053001/61722067-966c5780-ad37-11e9-81ea-06d7adc2f330.png)

We found a way to convert the folder of images into a single mha volume and it worked. Thank you.

**Comment by ywang336** [comment]
> > Sorry for interrupting again. I have tried your case images and they ran successfully, but the mask area on output images became black. Is that the correct result of the CLI executable?
> 
> You mean the area _outside_ the mask area on the output image? Or the mask area itself?
> 
> > Can this filter deal with 3D images in the 3D Slicer? Or it can only deal with 2D images as the CLI executable.
> 
> The CLI executable and the Slicer extension should both work with 3D volumes. Please try and let us know if they don't.
> 
> > And also is there any ways to read folders with CLI executable?
> 
> I think the CLI executable works best the MHA files, which can be single 2D images or 3D volumes. I think we faced issues trying to provide an entire folder as an input and hence did not implement that. You could batch convert the folder of images into a single MHA volume - that should work as an input to COLLAGE.

Sorry for interrupting again. I have tried the CLI executable and cases on another computer today. And the output images also turned out to be black on the mask area. Is that the correct result for it? Thanks for helping and hoping to hear from you.

Best,
Wang

**Comment by satishev** [comment]
Let me get it tested at our end and get back to you.

**Comment by ywang336** [comment]
> Let me get it tested at our end and get back to you.

Hi. How is your testing going on? We have tried to open the output images in Matlab today and found that the black area was not black actually. Each pixel has its own value, but all very small. I read your paper "Co-occurrence of Local Anisotropic Gradient Orientations (CoLlAGe): A new radiomics descriptor" again and found there were many steps to get the features. So may I ask what is the step till the CLI executable finished? How can I get the final features with the output of CLI executable? Do I need some other softwares? Thanks and hoping to hear from you.

Best,
Wang

**Comment by satishev** [comment]
What you found is what I was going to report back to you. The CLI executable computes the gradient entropy (i.e. COLLAGE) value at each pixel. You should not have to do anything additional other than use the values as required. Typically, these values only make sense in contrast to each other. So if you were to compare the COLLAGE values for images from class 1 vs class 2, you should find differences.

Things are going a little slower than usual as folks are out on vacation etc. Let me know if any other issues, and I'll try to get them addressed as soon as I can.

**Comment by ywang336** [comment]
> What you found is what I was going to report back to you. The CLI executable computes the gradient entropy (i.e. COLLAGE) value at each pixel. You should not have to do anything additional other than use the values as required. Typically, these values only make sense in contrast to each other. So if you were to compare the COLLAGE values for images from class 1 vs class 2, you should find differences.
> 
> Things are going a little slower than usual as folks are out on vacation etc. Let me know if any other issues, and I'll try to get them addressed as soon as I can.

Thanks a lot. I think I understand it and the meaning of its output. As I asked before, I noticed that there were files "VolumeImage" and "VolumeMask" in your cases that you put the slices together. But after running in the CLI executable, the output only has the first slice of the image, but not the other slices. I also tried our own image and the output was also only the first slice. So can the CLI executable really deal with 3D images? If could, how can I get the output of the other slices? Thanks again.

Best,
Wang

**Comment by ywang336** [comment]
> What you found is what I was going to report back to you. The CLI executable computes the gradient entropy (i.e. COLLAGE) value at each pixel. You should not have to do anything additional other than use the values as required. Typically, these values only make sense in contrast to each other. So if you were to compare the COLLAGE values for images from class 1 vs class 2, you should find differences.
> 
> Things are going a little slower than usual as folks are out on vacation etc. Let me know if any other issues, and I'll try to get them addressed as soon as I can.

Hi,

Thank you for helping earlier. We have discussed with our professor and decided to analysed our 2D images with CLI executable first. And of course if we have any publication we would cite your papers. We are still looking forward to hearing from you about how to either deal with 3D images with CLI executable or run the extension in 3DSlicer. They both have some problems when I tried. Anyway, thank you for helping us these days and we all appreciate that very much.

Best,
Wang

**Comment by satishev** [comment]
Thanks for letting us know. Will look into these bugs as soon as we can.

**Comment by satishev** [comment]
Hi, wanted to provide an update -- we have now completely rewritten this in Python.

This new release is being more actively developed and we will be working to better integrate it with platforms such as 3D Slicer.

Please check out the repo here: https://github.com/radxtools/collageradiomics
Docker images and Jupyter notebooks are provided to make it easier to run.
Any issues you face with using/building it should be raised at the corresponding issue tracker: https://github.com/radxtools/collageradiomics/issues
