### ISSUE TITLE
Help building as an independent executable

### ISSUE THREAD

**Issue by rkpandya** [algohary/SlicerExtension_ColiageFilter#5]
I am trying to build this as an independent executable without using Slicer. I see it required ITK 4.6.1, but the cmake configuration for this version of ITK fails and I tried to use the latest version of ITK instead. 

Now face the following errors:
Cannot open include file: 'itkPasteImageFilter.h': No such file or directory	
Cannot open include file: 'itkRegionOfInterestImageFilter.h': No such file or directory	
Cannot open include file: 'itkVectorIndexSelectionCastImageFilter': No such file or directory	

I am currently using CMake 3.16 and the Visual Studio 14 2015 generator

[CMakeLists.txt](https://github.com/ccipd/CoLlAGeSlicerExtension/files/3876330/CMakeLists.txt)
[CMakeLists.txt](https://github.com/ccipd/CoLlAGeSlicerExtension/files/3876331/CMakeLists.txt)

**Comment by satishev** [comment]
We are looking into releasing the source for the standalone executable, linked [here](https://collageradiomics.com/download/), which should allow you to do this. Will get back to you in a week or so, once we have worked out the details.

**Comment by rkpandya** [comment]
Thank you! Looking forward to the release.

**Comment by rkpandya** [comment]
Hello, any update on the standalone exe?

**Comment by satishev** [comment]
Unfortunately more code dependencies than we expected, so struggling through code reorganization.

Did the compiled executable I linked to above work at all?

**Comment by satishev** [comment]
Hi, After facing multiple issues -- we have now completely rewritten this in Python.

This new release is being more actively developed and we will be working to better integrate it with platforms as well.

Please check out the repo here: https://github.com/radxtools/collageradiomics
Any issues you face with using/building it should be raised at the corresponding issue tracker: https://github.com/radxtools/collageradiomics/issues
